- NewRelicExampleApp/ios/AgentTestApp.xcodeproj/project.pbxproj
- NewRelicExampleApp/ios/Podfile.lock
- NewRelicExampleApp/package.json
Updated the packages for the example app to use our agent v0.0.8
> Update example app

- README.md
- package.json
- Updating instructions to use Android agent `6.9.1`
- Updating devDependencies to more recent versions to mitigate vulnerabilities
> chore: update dependencies

- .github/workflows/release-testing.yaml
> chore: update npm token

- .github/workflows/update_native_agent_version.yml
GHA will update version number in `package.json`, which is used in corresponding gradle and podspec files. Also updates `README` to use latest android version.
> GHA to update version on native agent release

- newrelic-react-native-agent.podspec
https://issues.newrelic.com/browse/NR-93820
> feat: add Support For TVOS

- README.md
- new-relic/scripts/dsym-upload-scripts/newrelic_postbuild.sh
Adding instructions for dSYM upload for iOS to README
> docs: Add dSYM upload instructions

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/enhancement.md
Adding issue templates to help gather relevant information for resolving issues or adding new features.
> docs: Add issue templates

- README.md
- __mocks__/nrm-modular-agent.js
- android/src/main/java/com/NewRelic/NRMModularAgentModule.java
- index.js
- ios/bridge/NRMModularAgent.m
- jestSetup.js
- new-relic/__tests__/new-relic.spec.js
- new-relic/nrma-modular-agent-wrapper.js
- package.json
- Add shutdown method
- Update to latest native agents 6.11.0 and 7.4.4
> Add shutdown

- NewRelicExampleApp/React-Native-Test-App/android/app/build.gradle
- NewRelicExampleApp/React-Native-Test-App/android/build.gradle
- NewRelicExampleApp/React-Native-Test-App/android/gradle/wrapper/gradle-wrapper.properties
- NewRelicExampleApp/React-Native-Test-App/android/settings.gradle
- NewRelicExampleApp/React-Native-Test-App/ios/AwesomeProject-Bridging-Header.h
- NewRelicExampleApp/React-Native-Test-App/ios/AwesomeProject.xcodeproj/project.pbxproj
- NewRelicExampleApp/React-Native-Test-App/ios/Podfile.lock
- NewRelicExampleApp/React-Native-Test-App/ios/Test.swift
- NewRelicExampleApp/React-Native-Test-App/package.json
- package.json
> fix: fix for example app failed android build

- android/build.gradle
- android/src/main/java/com/NewRelic/NRMModularAgentModule.java
> fix: fix no class found error for recordHandledException method

- CHANGELOG.md
- NewRelicExampleApp/React-Native-Test-App/package.json
- ios/bridge/NRMModularAgent.m
- package.json
react native ios build is not compling because of duplicate method in ios module
#141
> fix: fix duplicate method issue

- CHANGELOG.md
- README.md
- __mocks__/nrm-modular-agent.js
- android/src/main/java/com/NewRelic/NRMModularAgentModule.java
- index.js
- ios/bridge/NRMModularAgent.m
- new-relic/__tests__/new-relic.spec.js
- new-relic/nrma-modular-agent-wrapper.js
- package.json
customers can get info regarding events, crashes and exceptions when user does not have internet connection.
#113,#147
> feat: added support for offline storage for events

- package.json
> chore: update expo config and android cli package

- CHANGELOG.md
- README.md
- index.js
- ios/bridge/NRMModularAgent.m
- new-relic/__tests__/new-relic.spec.js
- package.json
> feat: added backgroundReporting and NewEventSystem Configuration

- CHANGELOG.md
- README.md
- package.json
> chore: update Native Android Agent and Expo configs

- CHANGELOG.md
- package.json
Fixed an issue causing the application to crash when transitioning to the background due to a mismatch between the Android and NDK agents.
#183 #196
> fix: android app crashes when backgrounded

- CHANGELOG.md
- package.json
> docs: release 1.4.5

- CHANGELOG.md
- android/src/main/java/com/NewRelic/NRMModularAgentModuleImpl.java
- android/src/newarch/java/com/NewRelic/NRMModularAgentModule.java
- package.json
> fix: android build issue for new architecture

- new-relic/nrma-modular-agent-wrapper.js
fix https://github.com/newrelic/newrelic-react-native-agent/issues/230, as per https://github.com/newrelic/newrelic-react-native-agent/issues/230#issuecomment-2855202861
> fix: update internal modules to export syntax

- __mocks__/react-native.js
- __mocks__/react-native/Libraries/Core/Devtools/parseErrorStack.js
- __mocks__/react-native/Libraries/Core/Devtools/symbolicateStackTrace.js
- jest.config.js
- new-relic/nrma-modular-agent-wrapper.js
- package.json
Hopefully, this better addresses #230, as I imagine that the revert were the failing tests?
> fix: update import statements for error stack parsing
